language: generic

os:
  - linux
  - osx

sudo: false

before_script:
  - git clone --depth 1 https://github.com/thinca/vim-themis /tmp/vim-themis

script:
  - vim --version
  - /tmp/vim-themis/bin/themis
