language: generic

os:
  - linux
  - osx

sudo: false

cache:
  directories:
    - /tmp/vim-themis

before_script:
  - git clone https://github.com/thinca/vim-themis /tmp/vim-themis

script:
  - vim --version
  - /tmp/vim-themis/bin/themis
