version: '{build}'
clone_depth: 1
before_test:
  - cmd: git clone --depth 1 https://github.com/thinca/vim-themis %TEMP%\vim-themis
build: off
test_script:
  - cmd: |
    vim --version
    %TEMP%\vim-themis\bin\themis.bat
deploy: off
